### ISSUE TITLE
Support for beta versions.

### ISSUE THREAD

**Issue by alfablac** [faush01/playback_reporting#2]
Is it possible to add support for the 4.3.x beta versions of Emby?
At least relasing it as beta so we can check if it's buggy or not. Current version of Playback Reporting 1.6.7 shows as not compatible with version 4.3.0.19

**Comment by faush01** [comment]
A Emby 4.3 compatible version will be release when the Emby beta is released.
Unfortunately the plugin will break multiple times until the beta is released as stable and the time spent hitting a moving target is to great.
