### ISSUE TITLE
HTTP 400: Bad Request

### ISSUE THREAD

**Issue by tycrek** [faush01/playback_reporting#5]
For a while now I've been getting a `400:Bad Request` error in certain tabs tabs. Firefox network monitor shows the response is:

    Value cannot be null. (Parameter 'key')

**Comment by faush01** [comment]
The server log might have more info about the reason for the 400

Also what is the requested url and params, you should also be able to see them in the Firefox network monitor.

**Comment by tycrek** [comment]
**URL**: `http://10.235.0.3:8096/emby/user_usage_stats/PlayActivity?filter=Video,Movie,Episode,Audio&days=28&end_date=2020-07-02&data_type=time&stamp=1593697426687`

**Params**:

filter | "Video,Movie,Episode,Audio"
-- | --
days | `28`
end_date | `2020-07-02`
data_type | `time`
stamp | `1593697426687`

**Error from logs**:

```
2020-07-02 07:43:46.759 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.4.3.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.108
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	System.Environment.Version: 3.1.2
	Processor count: 12
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
	   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
	   at playback_reporting.Data.ActivityRepository.GetUsageForDays(Int32 days, DateTime end_date, String[] types, String data_type)
	   at playback_reporting.Api.UserActivityAPI.Get(GetUsageStats activity)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void ThrowArgumentNullException(System.ExceptionArgument)
```

**Comment by faush01** [comment]
This is probably due to a missing or unknown user.
If you remove users from your Emby system the reporting system can get confused and cause errors.
There is an action button under the settings tab:
"When you remove users from your system playback activity for old deleted users becomes assigned to unknown, you can remove this data to clean up your reports. "
With a button "cleanup deleted users"
Try this and see if it fixes your problem.

**Comment by tycrek** [comment]
Sorry for late reply. Tried that button, still get 400 Bad Request. Emby is version 4.4.3.0

**Comment by faush01** [comment]
ok, I will have.another look and see what I can find

**Comment by faush01** [comment]
for some reason it looks liek you have nulls in your userID field in the DB, I did not think this was possible but it could be a bug allowing this. To test this can you run the following query in the Query Tab

`
SELECT COUNT(1) AS RowCount 
FROM PlaybackActivity
WHERE UserId is null
`

This should return Zero results, if it does return results let me know what the count was.

If the above does return results and you want to get back up and running fast you can run the following command to remove the results with null user ids

`DELETE FROM PlaybackActivity WHERE UserId is null`

This will remove the useless entries.

**Comment by tycrek** [comment]
> `SELECT COUNT(1) AS RowCount FROM PlaybackActivity WHERE UserId is null`

Returns RowCount of 20. Running the `DELETE` query worked too. Not sure what the bug was.

Not getting HTTP 400 anymore, thanks for all your help and the quick replies!

**Comment by faush01** [comment]
ok thanks for reporting back, I will need to look at why and how nulls ended up in there, it should not be possible.

**Comment by faush01** [comment]
This should be fixed in the latest release.
