### ISSUE TITLE
Ressource Monitoring

### ISSUE THREAD

**Issue by dual-oo** [faush01/playback_reporting#6]
It was removed since the last version.
Will miss this nice feature.
Can we get more informations?

Thanks

**Comment by faush01** [comment]
This plugin is not the best place for monitoring system stats.

There are system monitoring and charting tools out there that can do this sort of thing much better.

In 15 minutes the other day I put together a Grafite monitoring system using postresql and python that logs emby playback stats and system info that is much more functional and configurable. If there is interest I can make that script available with steps on how to set it up.

**Comment by dual-oo** [comment]
100% agree... but to see the simultantious streams the last 24h was a nice feature.
Anyway you're right. Netdata / Grafana is a better place for this... would be nice to have such a solution for this.

thanks for your great work

**Comment by faush01** [comment]
in the next few days I will post my emby stats logging script to the emby forum.
