### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by dual-oo** [faush01/playback_reporting#7]
Hey,

it would be nice to get the data from "playback reporting" into a prometheus / grafana environment.
Is it possible to implement "/metrics" in the plugin to setup prometheus as a data scraper?

Thanks in advance

**Comment by faush01** [comment]
You should be able to use any of the existing API endpoints to do this. Each chart page has a number of API endpoints it gets the data from to build the charts, you should be able to use them to harvest the data.
