### ISSUE TITLE
Loading from backup - access denied

### ISSUE THREAD

**Issue by jaroslawjanas** [faush01/playback_reporting#8]
Can't seem to be able to load from a backup .tsv file.
I am running emby in docker but I'm pretty sure the file has read permissions inside docker.
![image](https://user-images.githubusercontent.com/28691446/96656435-b7a36580-1337-11eb-948c-0bc2baa78242.png)

Good work one the plugin, it's really good.

[EDIT]
Tested outside of docker, still the same problem.

**Comment by faush01** [comment]
Did the plugin create this file in this location?

The plugin runs a part of the Emby Server process with all the permissions that that process has, try dropping the file in your media path and see if can be accessed from there.
