### ISSUE TITLE
Some palette colors ignored, others over-used.

### ISSUE THREAD

**Issue by whiteowl3** [faush01/playback_reporting#9]
Some colors in the pallette do not get used.  I have 6 active users and 6 active custom colors, but PR insists on using only three of those colors to render the playback bar graph.  Each of the first three colors is used twice and the last 3 are ignored.
Great work everywhere else mate.  Thanks for publishing.
1.7.0.3 in 4.5.4.0 in ubuntu latest.

**Comment by faush01** [comment]
On which chart are to referring to?
The custom colours are used in to main places, the User Playback bar chart and the breakdown pie charts.
Which chart is not using all your colours?
Can you attach a screen shot, that might help.

**Comment by faush01** [comment]
This is what I see with 6 users
![image](https://user-images.githubusercontent.com/3616162/107308153-3a655180-6adc-11eb-808e-b050a5463cdb.png)

This is my colour palet
![image](https://user-images.githubusercontent.com/3616162/107308118-27eb1800-6adc-11eb-8c5f-a10fcdb59979.png)

**Comment by faush01** [comment]
This is probably the reason

```        // sort all user and assign colours
        var full_user_list = [];
        for (var i = 0; i < user_list.length; i++) {
            full_user_list.push(user_list[i].name);
        }

        full_user_list.sort();
        var user_colour_map = {};
        for (var x = 0; x < full_user_list.length; x++) {
            user_colour_map[full_user_list[x]] = color_list[x % color_list.length];
        }```

It tries to assign the colour to the user based on the full user list regardless of how nay users are in the current chart, this gives some stickiness to the user colour so as users gome and go from the playback report chart they keep the same colour.
This measn if you have 20 users and 10 colours in your colour palette 2 users will have the same colour and should always unless you add more users to the system have the same colour in the chart.
It could be you have just the correct number of users to "loop" the colours around and only the 6 users that are showing up in the chart have the same colours.
To test this add a few more colours or remove a few colours from your colour palette in the plugin settings, if the above is happening then you should see new colours assigned to the users.
